### ISSUE TITLE
Can't configure plugins

### ISSUE THREAD

**Issue by DLMousey** [vincelwt/harmony#197]
Issue seems to be present in 0.8.0 and 0.8.1 on windows (haven't tested on Linux/Mac), The list of plugins will scroll but i can't select any of them to sign in (i use facebook sign in for spotify and soundcloud).

Here's a GIF of the issue, Can assure you i'm mashing the absolute crap out of my mouse button ;)
![Fallback Link to GIF](https://puu.sh/yvNKQ/8bb15aa7cc.gif)

Also noticed after clearing settings and restarting Harmony that the theme selectors are empty
![image](https://user-images.githubusercontent.com/8281699/33370862-bcea5130-d4f0-11e7-850a-dc6c9e0a163e.png)

Possibly related issue is occuring with Plugin installation as well, After giving it the repo url for the harmony-plugins and hitting install nothing happens, Again no errors are logged to console.
Got another GIF of this issue
![Fallback Link to GIF](https://puu.sh/yvNUK/ebcbf0964f.gif)

Console reports no errors, Happening on Windows 10 (Ver 10.0.16299.64)

**Comment by vincelwt** [comment]
Hey! I thought I fixed this with 0.8.1 :/
Is there any error message if you open the console directly in the settings (if you can, we can't always)? 
Also could you try removing the file` C:\Users\<your username>\.config\configstore\harmony.json` and see if it helps when rebooting?
Thanks!

**Comment by DLMousey** [comment]
Couldn't get the console to open for the settings window unfortunately - only for the main window. Left it open while i prodded about the settings window nothing was logged, Also tried your fix of removing the `harmony.json` from configstore, That didn't seem to solve the problem either. Tried restarting Harmony on it's own first, Then removed the file again and did a full system reboot just to be sure but still no luck :(

**Comment by Ashchu117** [comment]
I am having the exact same issue 0.8.0 and 0.8.1

**Comment by vincelwt** [comment]
@DLMousey Thanks for trying, I'll do my best to get my hands on a windows machine see if I can reproduce as this seems to happen only on Windows

**Comment by DLMousey** [comment]
No problem, happy to help :) It's not _quite_ it's intended purpose but could the IE Testing VMs from Microsoft be an option for running your tests? https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

(tl;dr - Pre-built VirtualBox VMs that self-destruct after their temporary license term is up)

**Comment by vincelwt** [comment]
Thanks that's a good idea :) I was able to test and fix it yesterday! I'll test, build and upload the new version probably by tomorrow :)
But I'll definitely look up at setting up a vm for next time :P

**Comment by vincelwt** [comment]
Should be fixed :) could you try and confirm?

**Comment by DLMousey** [comment]
Yup that's got it 0.8.2 working fine for me on Windows 10 :) I'll close this issue

For anyone still having trouble after the update make sure you reset your settings (Preferences > General > Reset Settings) then relaunch Harmony
